USE [master]
GO

/****** Object:  Database [SMARTBUS]    Script Date: 18-Dec-19 2:02:36 AM ******/
CREATE DATABASE [SMARTBUS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMARTBUS', FILENAME = N'D:\SQLExpress2017\MSSQL14.SQLEXPRESS\MSSQL\DATA\SMARTBUS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SMARTBUS_log', FILENAME = N'D:\SQLExpress2017\MSSQL14.SQLEXPRESS\MSSQL\DATA\SMARTBUS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMARTBUS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SMARTBUS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SMARTBUS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SMARTBUS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SMARTBUS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SMARTBUS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SMARTBUS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SMARTBUS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SMARTBUS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SMARTBUS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SMARTBUS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SMARTBUS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SMARTBUS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SMARTBUS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SMARTBUS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SMARTBUS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SMARTBUS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SMARTBUS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SMARTBUS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SMARTBUS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SMARTBUS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SMARTBUS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SMARTBUS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SMARTBUS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SMARTBUS] SET  MULTI_USER 
GO

ALTER DATABASE [SMARTBUS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SMARTBUS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SMARTBUS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SMARTBUS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SMARTBUS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SMARTBUS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SMARTBUS] SET  READ_WRITE 
GO

